# Generated by Django 3.2.25 on 2024-12-12 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0002_auto_20241210_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='preferred_staff',
        ),
    ]
